[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "8.19.0"

# Configure lighthouse plugin to not fail builds
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    fail_build_on_error = false
    skip_lhci = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "max-age=31536000"

# 🔧 FIX: Add client-side routing support
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 