[build]
  command = "npm ci && npm run type-check && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "8.19.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "max-age=31536000"

# 🔧 FIX: Add client-side routing support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

 
